site_name: LibreIncu
site_description: 'Documentación LibreIncu'
site_author: 'AlterMundi-CTO'
site_url: 'https://altermundi-monitoreoycontrol.github.io/website/'  # REQUIRED for
docs_dir: docs/
extra_files: img/
repo_url: 'https://github.com/AlterMundi-MonitoreoyControl/website'
markdown_extensions:
  - attr_list
  - md_in_html

# SEO plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - meta-descriptions
  - redirects
  - git-revision-date-localized:
      enable_creation_date: true

# Theme configuration
theme:
  name: readthedocs  # or your preferred theme
  features:
    - navigation.top
    - search.highlight

# Enable SEO-friendly URLs
use_directory_urls: true

# Additional metadata
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlterMundi-MonitoreoyControl
    - icon: fontawesome/brands/twitter
      link: https://x.com/altermundinet
