site_name: LibreIncu
site_description: 'Documentación LibreIncu'
site_author: 'AlterMundi-CTO'
site_url: 'https://altermundi-monitoreoycontrol.github.io/website'  # REQUIRED for
docs_dir: docs/
extra_files: img/
repo_url: 'https://github.com/AlterMundi-MonitoreoyControl/website'
markdown_extensions:
  - attr_list
  - md_in_html

# SEO plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - meta-descriptions
  - redirects
  - git-revision-date-localized:
      enable_creation_date: true

# Theme configuration
theme:
  name: readthedocs  # or your preferred theme
  features:
    - navigation.top
    - search.highlight

# Enable SEO-friendly URLs
use_directory_urls: true

# Additional metadata
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlterMundi-MonitoreoyControl
    - icon: fontawesome/brands/twitter
      link: https://x.com/altermundinet
nav:
    - Inicio: index.md
    - Manual básico de incubadoras LibrePollo: "Manual básico de incubadoras LibrePollo.md"
    - Huevos Fértiles e Incubación: "Huevos Fértiles e Incubación.md"
    - LibrePollo - Aplicación: "LibrePollo - Aplicación.md"
    - Preguntas para Buenas Prácticas: "Preguntas para las Buenas Prácticas de Incubación.md"
    - Ecosistema informático: "Ecosistema informático para la agricultura familiar.md"
    - Especificaciones técnicas: "Especificaciones_técnicas.md"
    - Solución de problemas: "solucion de problemas.md"
    - Videos, prensa y difusión: "Videos_prensa_y_difusión.md"
    - Contacto: "Contacto.md"
