site_name: LibreIncu
site_description: 'Documentación LibreIncu'
site_author: 'AlterMundi-CTO'
docs_dir: docs/
repo_url: 'https://github.com/AlterMundi-MonitoreoyControl/website'
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption